/* eslint-disable @shopify/typescript/prefer-pascal-case-enums */
export enum SquareCommand {
  GET_ALL_CATALOG = 'GET_ALL_CATALOG',
  GET_BATCH_CATALOG = 'GET_BATCH_CATALOG',
  GET_ONE_CATALOG = 'GET_ONE_CATALOG',
  GET_ONE_INVENTORY = 'GET_ONE_INVENTORY',
  GET_OPTIONS_AND_ATTRIBUTES = 'GET_OPTIONS_AND_ATTRIBUTES',
  SEARCH_FOR_USER = 'SEARCH_FOR_USER'
}
