/* eslint-disable @shopify/typescript/prefer-pascal-case-enums */
export const SquareCommand = {
  GET_ALL_CATALOG: 'GET_ALL_CATALOG',
  GET_BATCH_CATALOG: 'GET_BATCH_CATALOG',
  GET_ONE_INVENTORY: 'GET_ONE_INVENTORY',
  GET_OPTIONS_AND_ATTRIBUTES: 'GET_OPTIONS_AND_ATTRIBUTES',
  SEARCH_FOR_USER: 'SEARCH_FOR_USER',
  GET_CUSTOMER: 'GET_CUSTOMER',
  TAKE_PAYMENT: 'TAKE_PAYMENT',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER'
} as const;
